name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        uses: php-actions/composer@v4
        with:
          php_version: 7.1
          composer_version: 1
#        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Doctrine Migrations
        uses: everphone-gmbh/doctrine-migrations-action@v0.9

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      # - name: Run test suite
      #   run: composer run-script test

      # - name: Run coding standards analysis
      #   run: composer run-script phpcs
